/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import Database.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        table();
    }
    
    void reset(){
        tfName.setText("");
        tfNpm.setText("");
        tfJurusan.setText("");
        rLaki.setSelected(false);
        rPerempuan.setSelected(false);
    }
    
void cari() {
    DefaultTableModel tbl = new DefaultTableModel();
    tbl.addColumn("npm");
    tbl.addColumn("nama");
    tbl.addColumn("jenis kelamin");
    tbl.addColumn("jurusan");
    
    try {
        String sql = "SELECT * FROM data_mahasiswa WHERE npm LIKE '%" + bCari2.getText() + "%'";
        Connection con = (Connection) Koneksi.getConnection();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        boolean found = false; // Menandai apakah ada hasil pencarian yang ditemukan
        while (rs.next()) {
            tbl.addRow(new Object[]{
                rs.getString("npm"),
                rs.getString("nama"),
                rs.getString("jenis_kelamin"),
                rs.getString("jurusan")
            });
            found = true; // Set found menjadi true karena ada hasil pencarian
        }
        if (!found) {
            // Jika tidak ada hasil pencarian, tampilkan pesan ke pengguna
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        tblMhs.setModel(tbl); // Set model tabel di luar loop while
    } catch (Exception e) {
        e.printStackTrace(); // Menampilkan trace stack lengkap
    }
}




    public void table(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("npm");
        tbl.addColumn("nama");
        tbl.addColumn("jenis kelamin");
        tbl.addColumn("jurusan");
        
        try {
            Statement st = (Statement) Koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM data_mahasiswa");
            while(rs.next()){
                tbl.addRow(new Object[]{
                    rs.getString("npm"),
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("jurusan")
                });
                tblMhs.setModel(tbl);
            }
            JOptionPane.showMessageDialog(null, "koneksi berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "koneksi gagal");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bHapus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNpm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfJurusan = new javax.swing.JTextField();
        bTampil = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        rLaki = new javax.swing.JRadioButton();
        rPerempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMhs = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bCari2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bHapus.setBackground(new java.awt.Color(255, 153, 0));
        bHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bHapusMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("CRUD");

        jLabel2.setText("NPM");

        jLabel3.setText("NAMA");

        jLabel4.setText("KELAMIN");

        jLabel5.setText("JURUSAN");

        bTampil.setText("TAMPIL");
        bTampil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTampilMouseClicked(evt);
            }
        });
        bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTampilActionPerformed(evt);
            }
        });

        bSimpan.setText("SIMPAN");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bEdit.setText("EDIT");
        bEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEditMouseClicked(evt);
            }
        });
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        rLaki.setText("laki-laki");

        rPerempuan.setText("perempuan");

        tblMhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMhs);

        jButton1.setText("HAPUS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        bCari2.setText("cari");
        bCari2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCari2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bHapusLayout = new javax.swing.GroupLayout(bHapus);
        bHapus.setLayout(bHapusLayout);
        bHapusLayout.setHorizontalGroup(
            bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bHapusLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(bHapusLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bHapusLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addComponent(tfNpm, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bHapusLayout.createSequentialGroup()
                        .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bHapusLayout.createSequentialGroup()
                                .addComponent(rLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bCari2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bHapusLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bHapusLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bHapusLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bHapusLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        bHapusLayout.setVerticalGroup(
            bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bHapusLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rLaki)
                    .addComponent(rPerempuan))
                .addGap(18, 18, 18)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTampil)
                    .addComponent(bSimpan)
                    .addComponent(bEdit)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addGroup(bHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bHapusMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM data_mahasiswa WHERE npm='" + tfNpm.getText() + "'";

            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (Exception e) {
            // Tanggapan terhadap eksepsi
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
            e.printStackTrace(); // Menampilkan jejak stack trace

            // Tambahkan pesan debug
            System.out.println("Pesan Debug: " + e.getMessage());
        }
    }//GEN-LAST:event_bHapusMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM data_mahasiswa WHERE npm='" + tfNpm.getText() + "'";

            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (Exception e) {
            // Tanggapan terhadap eksepsi
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
            e.printStackTrace(); // Menampilkan jejak stack trace

            // Tambahkan pesan debug
            System.out.println("Pesan Debug: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void tblMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhsMouseClicked
        // TODO add your handling code here:
        int baris = tblMhs.rowAtPoint(evt.getPoint());
        String npm = tblMhs.getValueAt(baris, 0).toString();
        tfNpm.setText(npm);
        String nama = tblMhs.getValueAt(baris, 1).toString();
        tfName.setText(nama);
        String jurusan = tblMhs.getValueAt(baris, 3).toString();
        tfJurusan.setText(jurusan);
    }//GEN-LAST:event_tblMhsMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        //        int baris = tblMhs.rowAtPoint(evt.getPoint());

    }//GEN-LAST:event_bEditActionPerformed

    private void bEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditMouseClicked
        // TODO add your handling code here:
        String jk = null;
        if (rLaki.isSelected()) {
            jk = "laki - laki";
        } else if (rPerempuan.isSelected()) {
            jk = "perempuan";
        }

        try {
            String sql = "UPDATE data_mahasiswa SET npm=?, nama=?, jenis_kelamin=?, jurusan=? WHERE npm=?";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            // Mengatur parameter pada PreparedStatement
            pst.setString(1, tfNpm.getText());
            pst.setString(2, tfName.getText());
            pst.setString(3, jk);
            pst.setString(4, tfJurusan.getText());
            pst.setString(5, tfNpm.getText()); // Kondisi WHERE
            // Eksekusi pernyataan SQL
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            // Tanggapan terhadap eksepsi
            JOptionPane.showMessageDialog(null, "Gagal mengedit data: " + e.getMessage());
            e.printStackTrace(); // Menampilkan jejak stack trace
        }
    }//GEN-LAST:event_bEditMouseClicked

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String jk = null;
        if (rLaki.isSelected()) {
            jk = "laki - laki";
        } else if (rPerempuan.isSelected()) { // Ganti dari rLaki.isSelected() ke rPerempuan.isSelected()
            jk = "perempuan";
        }

        try {
            String sql = "INSERT INTO `data_mahasiswa` (`nama`, `jenis_kelamin`, `npm`, `jurusan`) VALUES (?, ?, ?, ?)";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pat = con.prepareStatement(sql);
            pat.setString(1, tfName.getText());
            pat.setString(2, jk);
            pat.setString(3, tfNpm.getText());
            pat.setString(4, tfJurusan.getText());
            pat.execute();
            //        tblMhs.add(this);
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan: " + e.getMessage());
            e.printStackTrace(); // Menampilkan trace stack lengkap
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTampilActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM data_mahasiswa WHERE npm = '" + tfNpm.getText() + "'";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal ditampilkan: " + e.getMessage());
        }
    }//GEN-LAST:event_bTampilActionPerformed

    private void bTampilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTampilMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM data_mahasiswa WHERE npm = '" + tfNpm.getText() + "'";
            Connection con = (Connection) Koneksi.getConnection();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal ditampilkan: " + e.getMessage());
        }
        table();
        reset();
    }//GEN-LAST:event_bTampilMouseClicked

    private void bCari2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCari2MouseClicked
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_bCari2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari2;
    private javax.swing.JButton bEdit;
    private javax.swing.JPanel bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTampil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rLaki;
    private javax.swing.JRadioButton rPerempuan;
    private javax.swing.JTable tblMhs;
    private javax.swing.JTextField tfJurusan;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNpm;
    // End of variables declaration//GEN-END:variables
}
